---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fb-av-{{ .Values.environmentName }}"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "fb-av-{{ .Values.environmentName }}"
        appGroup: "fb-av"
        fb-service-token-cache-access: "false"
        tier: "frontend"
    spec:
      serviceAccountName: "formbuilder-av-{{ .Values.environmentName }}"
      containers:
      - name: "fb-av-{{ .Values.environmentName }}"
        image: "926803513772.dkr.ecr.eu-west-1.amazonaws.com/formbuilder/fb-av:latest-{{ .Values.platformEnv }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "1024Mi"
          limits:
            cpu: "1000m"
            memory: "2048Mi"
        ports:
          - containerPort: 3310
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-av-env-{{ .Values.environmentName }}
        env:
