kind: Service
apiVersion: v1
metadata:
  name: "fb-av-svc-{{ .Values.environmentName }}"
  labels:
    app: "fb-av-{{ .Values.environmentName }}"
    appGroup: "fb-av"
spec:
  ports:
  - port: 3310
    name: clamav
    targetPort: 3310
  selector:
    app: "fb-av-{{ .Values.environmentName }}"
