version: 2
jobs:
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-av
    docker: &ecr_image
      - image: $AWS_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh test'
      - run:
          name: deploy to test dev
          command: './scripts/circleci_deploy.sh test dev $KUBE_TOKEN_TEST_DEV'
      - run:
          name: deploy to test production
          command: './scripts/circleci_deploy.sh test production $KUBE_TOKEN_TEST_PRODUCTION'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh live'
      - run:
          name: deploy to live dev
          command: './scripts/circleci_deploy.sh live dev $KUBE_TOKEN_LIVE_DEV'
      - run:
          name: deploy to live production
          command: './scripts/circleci_deploy.sh live production $KUBE_TOKEN_LIVE_PRODUCTION'
  build_and_deploy_to_pentest:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh pentest'
      - run:
          name: deploy to pentest dev
          command: './scripts/circleci_deploy.sh pentest dev $KUBE_TOKEN_PENTEST_DEV'
      - run:
          name: deploy to pentest production
          command: './scripts/circleci_deploy.sh pentest production $KUBE_TOKEN_PENTEST_PRODUCTION'

workflows:
  version: 2
  build:
    jobs:
      - build_and_deploy_to_pentest:
          filters:
            branches:
              only:
                - master
                - deploy-to-pentest
      - build_and_deploy_to_test:
          filters:
            branches:
              only: master
      - confirm_live_deploy:
          type: approval
          requires:
            - build_and_deploy_to_test
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
