version: 2
jobs:
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-av
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh test'
      - run:
          name: deploy to test dev
          command: './scripts/circleci_deploy.sh test dev $KUBE_TOKEN_TEST_DEV $SENTRY_DSN_TEST'
      - run:
          name: deploy to test production
          command: './scripts/circleci_deploy.sh test production $KUBE_TOKEN_TEST_PRODUCTION $SENTRY_DSN_TEST'
  trigger_acceptance_tests:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - add_ssh_keys:
          fingerprints:
            - "36:f1:e3:84:63:24:2b:b8:e3:83:aa:cd:11:81:4c:01"
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: "Trigger Acceptance Tests"
          command: './deploy-scripts/bin/acceptance_tests'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh live'
      - run:
          name: deploy to live dev
          command: './scripts/circleci_deploy.sh live dev $KUBE_TOKEN_LIVE_DEV $SENTRY_DSN_TEST'
      - run:
          name: deploy to live production
          command: './scripts/circleci_deploy.sh live production $KUBE_TOKEN_LIVE_PRODUCTION $SENTRY_DSN_LIVE'

workflows:
  version: 2
  build:
    jobs:
      - build_and_deploy_to_test:
          filters:
            branches:
              only:
                - master
      - trigger_acceptance_tests:
          requires:
            - build_and_deploy_to_test
          filters:
            branches:
              only:
                - master
      - confirm_live_deploy:
          type: approval
          requires:
            - trigger_acceptance_tests
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
