apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Values.accessing_app }}-to-access-av
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: fb-av-{{ .Values.environmentName }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ .Values.accessing_app }}
    ports:
    - protocol: TCP
      port: 3310
